# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: step1
        run: |
          echo "success pattern"
          
        continue-on-error: true
      - name: Next Step
        env:
          STEP1_OUTCOME: ${{ steps.step1.outcome }}
        if: steps.step1.outcome != 'success'
        run: | 
          echo "This is the next step"
          echo "Step 1 outcome: ${{ env.STEP1_OUTCOME }}"
      - name: Post Step
        env:
          STEP1_OUTCOME: ${{ steps.step1.outcome }}
        if: steps.step1.outcome == 'success'
        run: | 
          echo "This is the post step"
          echo "Step 1 outcome: ${{ env.STEP1_OUTCOME }}"

  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    if: needs.job1.result != 'failure'
    env:
      JOB1_RESULT: ${{ needs.job1.result }}
      STEP1_RESULT: ${{ needs.job1.outputs.STEP1_OUTCOME }}
    steps:
      - name: Step 2
        run: |
          echo "This is Step 2"
          echo "Job 1 result: $JOB1_RESULT"
          echo "Step 1 outcome: $STEP1_RESULT"
